#include <iostream>
#include <fstream>
#include <string>
#include <filesystem>
#include <vector>

using namespace std;
namespace fs = std::filesystem;

void replaceSemicolons(fs::path& file) {
    ifstream input;

    input.open(file);

    if (!input.is_open()) {
        cerr << "Error opening file.";
        exit(1);
    }
    cout << "Loaded file.\n";

    string line;
    ofstream output;
    unsigned long long index = 1;
    fs::path outputName = file.parent_path() / ("changed" + file.extension().string());
    output.open(outputName);
    while (getline(input, line)) {
        cout << "REPLACING [" << index << "]: " << line << endl;
        if (line.find(';') != string::npos) {
            // replace semicolons with greek question mark (U+037E).
            line.replace(line.find(';'), 1, ";");
        }
        output << line << endl;
        cout << "SUCCESS   [" << index << "]: " << line << endl;
        index++;
    }

    output.close();
    cout << "Created file.\n";
}

int main() {
    const fs::path programPath = fs::current_path();
    fs::path path;

    cout << "Insert directory. If you want to use the same directory as the program type '0'.\n";
    cin >> path;
    if (path == "0") {
        path = programPath;
    }
    cout << "Selected path: " << path << endl;

    vector<fs::path> files;
    // https://stackoverflow.com/questions/612097/how-can-i-get-the-list-of-files-in-a-directory-using-c-or-c
    //
    // Windows will automatically replace forward slashes into backslashes. Source:
    // https://stackoverflow.com/questions/122455/handling-file-paths-cross-platform
    for (const auto & entry : fs::directory_iterator(path)) {
        // The following list of extensions was generated by chatGPT.
        if (fs::is_regular_file(entry.status()) &&
        (
            entry.path().extension() == ".txt" ||
            entry.path().extension() == ".c"   ||
            entry.path().extension() == ".cpp" ||
            entry.path().extension() == ".cc"  ||
            entry.path().extension() == ".cxx" ||
            entry.path().extension() == ".h"   ||
            entry.path().extension() == ".hpp" ||
            entry.path().extension() == ".hh"  ||
            entry.path().extension() == ".hxx" ||
            entry.path().extension() == ".java"||
            entry.path().extension() == ".cs"  ||
            entry.path().extension() == ".py"  ||
            entry.path().extension() == ".pyw" ||
            entry.path().extension() == ".js"  ||
            entry.path().extension() == ".mjs" ||
            entry.path().extension() == ".cjs" ||
            entry.path().extension() == ".ts"  ||
            entry.path().extension() == ".tsx" ||
            entry.path().extension() == ".go"  ||
            entry.path().extension() == ".rs"  ||
            entry.path().extension() == ".kt"  ||
            entry.path().extension() == ".kts" ||
            entry.path().extension() == ".swift"||
            entry.path().extension() == ".rb"  ||
            entry.path().extension() == ".php" ||
            entry.path().extension() == ".pl"  ||
            entry.path().extension() == ".pm"  ||
            entry.path().extension() == ".sh"  ||
            entry.path().extension() == ".bash"||
            entry.path().extension() == ".html"||
            entry.path().extension() == ".htm" ||
            entry.path().extension() == ".css" ||
            entry.path().extension() == ".sql" ||
            entry.path().extension() == ".r"   ||
            entry.path().extension() == ".R"   ||
            entry.path().extension() == ".dart"||
            entry.path().extension() == ".scala"
        )) {
            files.push_back(entry.path());
        }
    }

    cout << "\nAvailable files:\n";
    for (int i = 0; i < files.size(); i++) {
        cout << "[" << i << "] " << files[i] << endl;
    }

    unsigned short select;
    cout << "\nSelect the file you want to edit: \n";
    cin >> select;
    cout << "Selected file: " << files[select] << endl;

    replaceSemicolons(files[select]);

    return 0;
}